### ISSUE TITLE
Question and a Word!

### ISSUE THREAD

**Issue by loneicewolf** [bitcynth/blahajfs#5]
Hello! I browsed trough some repos and came across this one, (I am a swede as well) - I just had to say the name of this repo is brilliant, it made me smile! (blåhaj/blahaj fs), and this also made me have one question, the `README` says 
Every file is a blåhaj, and being swede I know what the blåhaj is - but what is it **in this context?** `:)`

Thanks! Take care

**Comment by bitcynth** [comment]
This is specifically about the BLÅHAJ plushie :)

**Comment by loneicewolf** [comment]
Oh okay, it was that one I thought of but I am still wondering what a blahaj file is `:P` anyway, have a good day! Thanks for Replying as well!

**Comment by bitcynth** [comment]
It is either a JPEG file with a picture of one or a plain text file saying blåhaj :)

**Comment by loneicewolf** [comment]
**Oh okay!** Unique project, really!  `:)` made me smile once more. 😄
